#根配置
baseURL = 'https://mxxws.github.io/'
languageCode = 'en-us'
title = '梦醒细无声の世界'
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'

[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"


#菜单配置

[menu]
  [[menu.main]]
    identifier = "archives"
    parent = ""
    pre = ""
    post = ""
    name = "归档"
    url = "/archives/"
    title = ""
    weight = 1
    [menu.main.params]
      icon = "fa-solid fa-archive"
  [[menu.main]]
    identifier = "categories"
    parent = ""
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
  [[menu.main]]
    identifier = "tags"
    parent = ""
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"


#插件配置

[params]
  version = "0.3.X"
  description = "梦醒细无声の世界"
  keywords = ["梦醒细无声", "blog", "落花世界又逢君"]
  
  #作者配置
  [params.author]
    name = "梦醒细无声"
    email = ""
    link = "https://mxxws.github.io/"
    avatar = "https://github.com/mxxws/picx-images-hosting/raw/master/mxxws-avatar.2ks3sf9q4a.webp"
  
  #主页配置
  [params.home]
    paginate = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "https://github.com/mxxws/picx-images-hosting/raw/master/mxxws-avatar.2ks3sf9q4a.webp"
      avatarMenu = ""
      title = "梦醒细无声"
      subtitle = "业精于勤，荒于嬉；行成于思，毁于随。"
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6

    [params.social]
      Email = "ccafder@gmail.com"
      Github = "mxxws"


  #不蒜子计数器配置
  [params.busuanzi]
    enable = true
    source = "https://vercount.one/js"
    siteViews = true
    pageViews = true

  #阅读进度条配置
  [params.readingProgress]
    enable = true
    start = "left"
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"

  #搜索配置
  [params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false
  
  #页面底部信息配置
  [params.footer]
    enable = true
    copyright = true
    author = true
    since = "2025"
    gov = ""
    icp = ""
    license = ""
    [params.footer.powered]
      enable = true
      hugoLogo = true
      themeLogo = true
    [params.footer.siteTime]
      enable = false
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = ""
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0

  #文章页面配置
  [params.page]
    #  是否启用文章作者头像
    authorAvatar = true
    # 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    #  是否在相关文章中隐藏一篇文章
    hiddenFromRelated = false
    #  是否在 RSS、Atom 和 JSON feed 中隐藏一篇文章
    hiddenFromFeed = false
    # 是否使用 twemoji
    twemoji = false
    #  是否使用 lightgallery
    # 设为 true，图片设置标题时，文章中的图片将以画廊形式呈现，例如：![alt](src "title")
    # 设为 "force"，无论图片是否设置标题文章中的图片都将强制按照画廊形式呈现，例如：![alt](src)
    lightgallery = false
    # 是否使用 ruby 扩展语法
    ruby = true
    # 是否使用 fraction 扩展语法
    fraction = true
    # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
    # 是否显示原始 Markdown 文档内容的链接
    linkToMarkdown = true
    #  是否显示查看文章源码的链接
    linkToSource = true
    #  是否显示编辑文章的链接
    linkToEdit = true
    #  是否显示报告文章问题的链接
    linkToReport = true
    #  页面样式 ["narrow", "normal", "wide", ...]
    pageStyle = "normal"
    #  开启自动书签支持
    # 如果为 true，则在关闭页面时保存阅读进度
    autoBookmark = false
    #  是否使用 字数统计
    wordCount = true
    #  是否使用 预计阅读
    readingTime = true
    #  文章结束标志
    endFlag = ""
    #  是否开启即时页面
    instantPage = false
    #  是否在侧边栏显示集合列表
    collectionList = false
    #  是否在文章末尾显示集合导航
    collectionNavigation = false

    #  转载配置
    [params.page.repost]
      enable = false
      url = ""
    # 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
      #  目录位置 ["left", "right"]
      position = "right"
      #  取代 `markup.tableOfContents` 设置
      ordered = false
      startLevel = 2
      endLevel = 6
    #  在文章开头显示提示信息，提醒读者文章内容可能过时
    [params.page.expirationReminder]
      enable = false
      # 如果文章最后更新于这天数之前，显示提醒
      reminder = 90
      # 如果文章最后更新于这天数之前，显示警告
      warning = 180
      # 如果文章到期是否关闭评论
      closeComment = false
    #  页面标题配置
    [params.page.heading]
      #  是否自动大写标题
      capitalize = false
      #  必须设置 `params.page.toc.ordered` 为 true
      [params.page.heading.number]
        # 是否启用自动标题编号
        enable = false
        [params.page.heading.number.format]
          h1 = "{title}"
          h2 = "{h2} {title}"
          h3 = "{h2}.{h3} {title}"
          h4 = "{h2}.{h3}.{h4} {title}"
          h5 = "{h2}.{h3}.{h4}.{h5} {title}"
          h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
    # 代码块包装器配置
    [params.page.code]
      #  是否启用代码块包装器
      enable = true
      # 是否显示代码块包装器的复制按钮
      copy = true
      #  是否显示代码块包装器的编辑按钮
      edit = true
      # 默认展开显示的代码行数
      maxShownLines = 10
    # KaTeX 数学公式 (https://katex.org)
    [params.page.math]
      enable = true
      # 默认行内定界符是 $ ... $ 和 \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v11"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v11"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    #  [试验性功能] 缓存图床图片到本地，详见：https://github.com/hugo-fixit/FixIt/pull/362
    [params.page.cacheRemoteImages]
      enable = false
      # 用本地图片链接替换远程图片链接 (放置在 public/images/remote/)
      replace = false
    #  相关内容配置 (https://gohugo.io/content-management/related/)
    [params.page.related]
      enable = false
      count = 5
    #  赞赏设置
    [params.page.reward]
      enable = false
      animation = false
      # 相对于页脚的位置，可选值：["before", "after"]
      position = "after"
      # comment = "Buy me a coffee"
      #  二维码图片展示模式，可选值：["static", "fixed"]，默认：`static`
      mode = "static"
      [params.page.reward.ways]
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        # paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"

    # social share links in post page
    [params.page.share]
      enable = false
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

    [params.page.comment]
      enable = true
      # FixIt 0.2.14 | NEW Giscus comments config
      [params.page.comment.giscus]
        enable = true
        repo = "mxxws/mxxws.github.io"
        repoId = "R_kgDOOYdrUw"
        category = "Announcements"
        categoryId = "DIC_kwDOOYdrU84CpHtI"
        mapping = "pathname"
        origin = "https://giscus.app" # FixIt NEW | 0.3.7 Or set it to your self-hosted domain
        strict = "0" # FixIt NEW | 0.2.18
        term = ""
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom" # ["top", "bottom"]
        lang = "zh-CN"
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
