name: Deploy Hugo Site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # 确保获取完整的 Git 历史

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.145.0"
          extended: true  # 使用 Hugo 扩展版（支持 Sass/SCSS）

      - name: Build
        run: hugo --minify --gc --cleanDestinationDir  # 精简命令

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          # 可选：添加 commit 信息
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"